export const LEGAL_KNOWLEDGE_BASE = [
  {
    id: 'law-001',
    sourceName: 'The Transfer of Property Act, 1882',
    title: 'Section 106 — Duration of certain leases in absence of written contract or local usage',
    section: 'Section 106',
    jurisdiction: 'India (Central)',
    sourceType: 'legislation',
    authorityLevel: 'primary',
    effectiveFrom: '1882-07-01',
    effectiveTo: null,
    version: 'Current (Amended 2002)',
    sourceUrl: 'https://indiacode.nic.in/handle/123456789/2338?view_type=browse&sam_handle=123456789/1362',
    lastVerifiedAt: '2026-01-15',
    text: 'In the absence of a contract or local law or usage to the contrary, a lease of immovable property for agricultural or manufacturing purposes shall be deemed to be a lease from year to year, terminable, on the part of either lessor or lessee, by six months\' notice; and a lease of immovable property for any other purpose shall be deemed to be a lease from month to month, terminable, on the part of either lessor or lessee, by fifteen days\' notice expiring with the end of a month of the tenancy.'
  },
  {
    id: 'law-002',
    sourceName: 'The Transfer of Property Act, 1882',
    title: 'Section 111 — Determination of lease',
    section: 'Section 111(g) & (h)',
    jurisdiction: 'India (Central)',
    sourceType: 'legislation',
    authorityLevel: 'primary',
    effectiveFrom: '1882-07-01',
    effectiveTo: null,
    version: 'Current',
    sourceUrl: 'https://indiacode.nic.in/handle/123456789/2338',
    lastVerifiedAt: '2026-01-15',
    text: 'A lease of immovable property determines by efflux of the time limited thereby; or by the expiration of a notice to determine the lease, or to quit, or of intention to quit, the property leased, duly given by one party to the other.'
  },
  {
    id: 'law-003',
    sourceName: 'The Indian Contract Act, 1872',
    title: 'Section 73 — Compensation for loss or damage caused by breach of contract',
    section: 'Section 73',
    jurisdiction: 'India (Central)',
    sourceType: 'legislation',
    authorityLevel: 'primary',
    effectiveFrom: '1872-09-01',
    effectiveTo: null,
    version: 'Current',
    sourceUrl: 'https://indiacode.nic.in/handle/123456789/2187',
    lastVerifiedAt: '2026-01-15',
    text: 'When a contract has been broken, the party who suffers by such breach is entitled to receive, from the party who has broken the contract, compensation for any loss or damage caused to him thereby, which naturally arose in the usual course of things from such breach, or which the parties knew, when they made the contract, to be likely to result from the breach of it.'
  },
  {
    id: 'law-004',
    sourceName: 'The Indian Contract Act, 1872',
    title: 'Section 74 — Compensation for breach of contract where penalty stipulated for',
    section: 'Section 74',
    jurisdiction: 'India (Central)',
    sourceType: 'legislation',
    authorityLevel: 'primary',
    effectiveFrom: '1872-09-01',
    effectiveTo: null,
    version: 'Current',
    sourceUrl: 'https://indiacode.nic.in/handle/123456789/2187',
    lastVerifiedAt: '2026-01-15',
    text: 'When a contract has been broken, if a sum is named in the contract as the amount to be paid in case of such breach, or if the contract contains any other stipulation by way of penalty, the party complaining of the breach is entitled, whether or not actual damage or loss is proved to have been caused thereby, to receive from the party who has broken the contract reasonable compensation not exceeding the amount so named or, as the case may be, the penalty stipulated for.'
  },
  {
    id: 'law-005',
    sourceName: 'Supreme Court of India — Kailash Nath Associates v. Delhi Development Authority (2015) 4 SCC 136',
    title: 'Judicial Precedent on Liquidated Damages vs Forfeiture of Deposit',
    section: 'Paras 38-43',
    jurisdiction: 'India (Supreme Court)',
    sourceType: 'judicial_precedent',
    authorityLevel: 'binding_precedent',
    effectiveFrom: '2015-01-09',
    effectiveTo: null,
    version: 'Reported',
    sourceUrl: 'https://main.sci.gov.in/judgment/judis/42247.pdf',
    lastVerifiedAt: '2026-01-15',
    text: 'Under Section 74 of the Indian Contract Act, damage or loss is not dispensed with. Where it is possible to prove actual damage or loss, such proof is not dispensed with. It is only in cases where damage or loss is difficult or impossible to prove that the liquidated amount named in the contract can be awarded as reasonable compensation. Forfeiture of earnest money or security deposits without genuine pre-estimate of loss is invalid.'
  },
  {
    id: 'law-006',
    sourceName: 'Model Tenancy Act, 2021 (Ministry of Housing and Urban Affairs)',
    title: 'Chapter V — Rights and Responsibilities of Landlord and Tenant',
    section: 'Section 21 & Section 22',
    jurisdiction: 'India (Model State Framework)',
    sourceType: 'model_legislation',
    authorityLevel: 'guideline_statute',
    effectiveFrom: '2021-06-02',
    effectiveTo: null,
    version: 'Adopted across various state tenancy reforms',
    sourceUrl: 'https://mohua.gov.in/upload/uploadfiles/files/Model_Tenancy_Act_English.pdf',
    lastVerifiedAt: '2026-01-15',
    text: 'The tenancy shall continue for the period agreed between the landlord and tenant in the tenancy agreement. The tenant may terminate the tenancy agreement before the expiry of the period by giving notice as specified in the tenancy agreement or in absence of specific provision, by giving at least one month notice to the landlord.'
  },
  {
    id: 'law-007',
    sourceName: 'The Indian Contract Act, 1872',
    title: 'Section 27 — Agreement in restraint of trade, void',
    section: 'Section 27',
    jurisdiction: 'India (Central)',
    sourceType: 'legislation',
    authorityLevel: 'primary',
    effectiveFrom: '1872-09-01',
    effectiveTo: null,
    version: 'Current',
    sourceUrl: 'https://indiacode.nic.in/handle/123456789/2187',
    lastVerifiedAt: '2026-01-15',
    text: 'Every agreement by which any one is restrained from exercising a lawful profession, trade or business of any kind, is to that extent void. Exception: One who sells goodwill of business with agreement with buyer to refrain from carrying on similar business within specified local limits.'
  },
  {
    id: 'law-008',
    sourceName: 'Supreme Court of India — Niranjan Shankar Golikari v. Century Spg. & Mfg. Co. Ltd. (1967) 2 SCR 378',
    title: 'Enforceability of Post-Termination Non-Compete Clauses in Employment Contracts',
    section: 'Paras 12-16',
    jurisdiction: 'India (Supreme Court)',
    sourceType: 'judicial_precedent',
    authorityLevel: 'binding_precedent',
    effectiveFrom: '1967-01-17',
    effectiveTo: null,
    version: 'Reported',
    sourceUrl: 'https://main.sci.gov.in',
    lastVerifiedAt: '2026-01-15',
    text: 'Negative covenants operative during the period of employment when the employee is bound to serve the employer exclusively are generally not regarded as restraint of trade under Section 27. However, negative covenants operating after the termination of employment are void and unenforceable under Indian Law.'
  }
];
